ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'BOMB', 'WAIT']
NUMBER_OF_CHANNELS = 3
MAZE_WIDTH = 17
MAZE_HEIGHT = 17
FEATURE_SHAPE = (NUMBER_OF_CHANNELS, MAZE_WIDTH, MAZE_HEIGHT)
BATCH_SIZE = 100_000_00#5000
MEMORY_SIZE = 100_000
INPUT_DIMENSIONS = (BATCH_SIZE, NUMBER_OF_CHANNELS, MAZE_WIDTH, MAZE_HEIGHT)
